config/routes.rb
Rails.application.routes.draw do
  get 'gallery/index'

  resources :categories
  resources :products
  resources :events

   root 'home#index'

  get 'products' => 'products#index'

  get 'house_of_code' => 'hoc#index'

  get 'rails_training' => 'rails_training#index'

  get 'blog' => 'blog#index'
  get 'blog/:id' => 'blog#show', as: 'article'

  get 'our_story' => 'story#index'

  resources :jobs

  get 'contact' => 'contact#index'

  get 'admin' => 'admin#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :article_tags
  has_many :tags, :through => :article_tags
  belongs_to :category
end

app/models/article_tag.rb
class ArticleTag < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  has_one :user
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :gallery
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :article_tags
  has_many :articles, :through => :article_tags
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  has_many :articles
  belongs_to :comment
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/hoc_helper.rb
module HocHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/views/layouts/_admin_nav.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><span>Lumino</span>Admin</a>
      <ul class="user-menu">
        <li class="dropdown pull-right">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>
            User <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/_footer.erb
<footer id="footer">
  <div class="container">
    <div class="row margin-bottom-60">
      <div class="col-sm-4 margin-bottom-30">
        <div class="footer-inner">
          <h3><a href="index.html"><img src="images/logo-dark.png" alt=""></a></h3>

          <p>

            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.
          </p>

          <div class="divided-30"></div>
          <ul class="social list-inline">
            <li><a href="#" class="fb"><i class="ion-social-facebook-outline"></i></a></li>
            <li><a href="#" class="twitter"><i class="ion-social-twitter-outline"></i></a></li>
            <li><a href="#" class="in"><i class="ion-social-linkedin-outline"></i></a></li>
            <li><a href="#" class="dribbble"><i class="ion-social-dribbble-outline"></i></a></li>
          </ul>
        </div>
        <!--fotter inner-->
      </div>

      <div class="col-sm-4 margin-bottom-30">
        <div class="footer-inner">
          <h3>Contact us</h3>

          <ul class="list-unstyled contact-list">
            <li><i class="ion-ios-home"></i> - Headquarters</li>
            <li><i class="ion-ios-analytics"></i> - P.O. Box 6563, Kampala Uganda</li>
            <li><i class="ion-ios-home"></i> - Kati House, Nakasero
              Kampala,Uganda.
            </li>
            <li><i class="ion-ios-telephone"></i> - +256 757 112 376</li>
            <li><i class="ion-ios-email"></i> Email: info@todidea.org</li>
          </ul>
        </div>
        <!--fotter inner-->
      </div>
      <div class="col-sm-4">
        <div class="footer-inner">
          <h3>Newsletter</h3>

          <p>
            Subscribe to our newsletter and get free updates
          </p>

          <form role="form" class="subscribe-form form-inline">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Enter email to subscribe">

              <button class="btn btn-default" data-toggle="tooltip" title="" data-original-title="Subscribe" type="submit">
                <i class="ion-ios-paperplane"></i></button>

            </div>
          </form>
        </div>
        <!--fotter inner-->
      </div>
    </div>
    <hr>
    <span class="clearfix copyright">&copy; 2015. All right reserved. Rainbow Connection Uganda</span>
  </div>
</footer>

app/views/layouts/_navigation.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><%= image_tag("logo.png", alt: "") %></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li class="<%= 'active' if params[:controller] == 'home' %>"><%= link_to("Home", root_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to("Products", products_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'events' %>"><%= link_to("Events", events_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'hoc' %>"><%= link_to("House Of Code", house_of_code_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'rails_training' %>"><%= link_to("Rails Training", rails_training_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'jobs' %>"><%= link_to("Jobs", events_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'blog' %>"><%= link_to("Blog", blog_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'contact' %>"><%= link_to("Contact", contact_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'story' %>"><%= link_to("Our Story", our_story_path) %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if params[:controller] == 'story' %>"><%= link_to("Login", root_path) %></li>
        <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to("Sign Up", products_path) %></li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
  <!--/.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TODIdea</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Custom google Fonts -->
  <!--<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Arimo:300,400,700,400italic,700italic'>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  &lt;!&ndash; HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries &ndash;&gt;
  &lt;!&ndash; WARNING: Respond.js doesn't work if you view the page via file:// &ndash;&gt;
  &lt;!&ndash;[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]&ndash;&gt;-->
</head>
<body>

<header>

  <% if params[:controller] != 'admin' %>
      <%= render 'layouts/navigation' %>
  <% else %>
      <%= render 'layouts/admin_nav' %>
  <% end %>

</header>
<!--header end-->

<div class="">
  <%= yield %>
</div>

<!--footer -->
<% if params[:controller] != 'admin' %>
    <%= render 'layouts/footer' %>
<% end %>
</body>
</html>